<a href="https://colab.research.google.com/github/ElzodQurashev/DS-AI_praktikum/blob/ds_practicum/modul_2_Pandas_Kutibxonasi_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### 2.2 Pandas kutubxonasi bilan tanishuv



**`pandas`** kutubxonasi ma'lumotlar muhandisining eng muhim ish quroli hisoblanadi. Data Science loyihalar ustida ishlar ekanmiz, 90% amallar aynan **`pandas`** yordamida amalga oshiriladi. **`pandas`** o'zining maxsus ma'lumotlar tuzilmalariga ega va bu tuzilmalar ma'lumotlarga ishlov berish, tozalash va boshqa amllarni bir necha barobar osonlashtiradi.

Avvalgi bo'limda ko'rilgan **`numpy`** kutubxonasidan farqli ravishda, **`pandas`** kutubxonasi faqatgina sonlardan iborat massivlar bilan emas, balki turli ko'rinishdagi ma'lumotlardan iborat jadvallar bilan ishlashga moslashgan.

In [2]:
import pandas as pd   # Pandas library
import numpy as np   # NumPy library
from pandas import Series   # Series ma'lumotlar tuzilmasi

# **# 0 *``Series`` ma'lumotlar tuzilmasi*** 

In [2]:
obj = Series([4, 5, 6, -6.5])   # Oddiy va sodda Series tuzish   
obj

0    4.0
1    5.0
2    6.0
3   -6.5
dtype: float64

In [3]:
type(obj)   # Ma'lumot turini tekshirish (demak bu Series)

pandas.core.series.Series

In [4]:
obj.values    # Series qiymatlari

array([ 4. ,  5. ,  6. , -6.5])

In [5]:
obj.index   # Series indekslari

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj[0]

4.0

In [30]:

#  index berish
obj2 = Series([6, 3, 2, 5], index = ['a','b','c','d'])
obj2

a    6
b    3
c    2
d    5
dtype: int64

In [8]:
obj2['a']   # indeks bo'yicha murojaat

6

In [9]:
obj2[['d','b','a']]   # bir nechta indeks bo'yicha murojaat

d    5
b    3
a    6
dtype: int64

In [10]:
obj2[['d','d','d']]   # bir necha marta bir xil indeksga murojaat

d    5
d    5
d    5
dtype: int64

In [11]:
obj2['x'] = 7   # yangi indeks va element qo'shish
obj2

a    6
b    3
c    2
d    5
x    7
dtype: int64

In [12]:
#  filtrga misol
obj2[obj2>4]    # obj2 ni 4 dan katta qiymatga ega bo'lganlarini chaqirish

a    6
d    5
x    7
dtype: int64

In [13]:
np.sort(obj2)   # tartiblangan ko'rinishi (asl ma'lumot o'zgarmaydi)

array([2, 3, 5, 6, 7])

In [32]:
obj2*2    # ko'paytirish, bo'lish, qo'shish, ayirish 

a    8
b    5
c    4
d    7
dtype: int64

In [15]:
np.exp(obj2)    # eksponenta

a     403.428793
b      20.085537
c       7.389056
d     148.413159
x    1096.633158
dtype: float64

# **# 1 *Lug'atdan  Series***

In [34]:
# Dictionary (lug'at)
cars_dict = {'Malibu':40000, 'Lacetti':20000, 'Toyota':45000, 'Mazda':52000, 'Honda':38000}
type(cars_dict)

dict

In [35]:
# Series from dict (lug'atdan Series)
cars1 = Series(cars_dict)
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [36]:
type(cars1)   # turi

pandas.core.series.Series

In [37]:
'Malibu' in cars1   # element Seriesda borligini tekshirish

True

In [38]:
'BMW' in cars1   # element Seriesda borligini tekshirish

False

In [39]:
cars1['Toyota']   # indeks bo'yicha murojaat

45000

In [40]:
# List (ro'yxat) indeks uchun.
models = ['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota', 'BMW']

In [41]:
cars2 = Series(cars_dict, index = models)   # avvaldan yozib olingan o'zgaruvchi orqali ineks berish
cars2                                       # elementi yo'q indekslar NaN qiymat oladi

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [42]:
# cars2['Jaguar'] = 30000
# cars2

# **# 2** ***Series metodlari***

In [47]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [48]:
# isnull()
cars2.isnull()    # NaN qiymatlar borligini tekshirish

Honda      False
Mazda      False
Lacetti    False
Jaguar      True
Malibu     False
Toyota     False
BMW         True
dtype: bool

In [49]:
# notnull()    # NaN qiymatlar yo'qligini tekshirish
cars2.notnull()

Honda       True
Mazda       True
Lacetti     True
Jaguar     False
Malibu      True
Toyota      True
BMW        False
dtype: bool

In [50]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [51]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [52]:
# Qo'shish
cars1+cars2

BMW             NaN
Honda       76000.0
Jaguar          NaN
Lacetti     40000.0
Malibu      80000.0
Mazda      104000.0
Toyota      90000.0
dtype: float64

In [53]:
# Nom berish (name), (index.name) Seriesga va indeksga nom berish
cars2.name = 'Avtosalon'
cars2.index.name = 'Car Models'

In [54]:
cars2

Car Models
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
Name: Avtosalon, dtype: float64

In [55]:
cars2.name

'Avtosalon'

In [56]:
cars2.index.name

'Car Models'

## **`Series` obyektiga oid ba'zi parametr va metodlar**

---




In [57]:
cars2

Car Models
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
Name: Avtosalon, dtype: float64

In [58]:
cars2.index    # Series.indexes

Index(['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota', 'BMW'], dtype='object', name='Car Models')

In [59]:
cars2.values    # Series.values

array([38000., 52000., 20000.,    nan, 40000., 45000.,    nan])

In [60]:
# .hasnans
cars2.hasnans   # NaN qiymatlar borligi "True" yo'qligi "False"

True

In [61]:
# dtype
cars2.dtype

dtype('float64')

In [62]:
cars2.is_unique    # qiymatlar takrorlanmas ekanini tekshirish

False

In [63]:
cars2.shape    # Series hajmi

(7,)

In [64]:
cars2.size    # Series hajmi

7

In [65]:
# iloc
cars2.iloc[2]    # ma'lumotlarga indeks tartib raqami bo'yicha murojaat qilish

20000.0

In [66]:
cars2.iloc[-1]

nan

In [67]:
cars2['Honda']    # ma'lumotlarga indeks bo'yicha murojaat qilish

38000.0

In [68]:
# loc
cars2.loc['Toyota']    # ma'lumotlarga indeks bo'yicha murojaat qilish

45000.0

In [69]:
cars2.max()    # max qiymat 

52000.0

In [70]:
cars2.min()    # min qiymat

20000.0

In [71]:
cars2.mean()    # o'rtacha qiymat

39000.0

In [72]:
cars2.sum()    # cars2 sum

195000.0

In [73]:
np.sum(cars2)    # cars2 sum

195000.0

In [74]:
next = " Keyingi dars DataFrame ma'lumotlar tuzilmasi "