<a href="https://colab.research.google.com/github/ElzodQurashev/DS-AI_praktikum/blob/ds_practicum/modul_2_Pandas_Kutibxonasi_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### 2.2 Pandas kutubxonasi bilan tanishuv



**`pandas`** kutubxonasi ma'lumotlar muhandisining eng muhim ish quroli hisoblanadi. Data Science loyihalar ustida ishlar ekanmiz, 90% amallar aynan **`pandas`** yordamida amalga oshiriladi. **`pandas`** o'zining maxsus ma'lumotlar tuzilmalariga ega va bu tuzilmalar ma'lumotlarga ishlov berish, tozalash va boshqa amllarni bir necha barobar osonlashtiradi.

Avvalgi bo'limda ko'rilgan **`numpy`** kutubxonasidan farqli ravishda, **`pandas`** kutubxonasi faqatgina sonlardan iborat massivlar bilan emas, balki turli ko'rinishdagi ma'lumotlardan iborat jadvallar bilan ishlashga moslashgan.

In [1]:
import pandas as pd   # Pandas library
import numpy as np   # NumPy library
from pandas import Series   # Series ma'lumotlar tuzilmasi

# **# 0 *``Series`` ma'lumotlar tuzilmasi*** 

In [2]:
obj = Series([4, 5, 6, -6.5])
obj

0    4.0
1    5.0
2    6.0
3   -6.5
dtype: float64

In [3]:
type(obj)

pandas.core.series.Series

In [4]:
obj.values

array([ 4. ,  5. ,  6. , -6.5])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj[0]

4.0

In [7]:
#  index berish
obj2 = Series([6, 3, 2, 5], index = ['a','b','c','d'])
obj2

a    6
b    3
c    2
d    5
dtype: int64

In [8]:
obj2['a']

6

In [9]:
obj2[['d','b','a']]

d    5
b    3
a    6
dtype: int64

In [10]:
obj2[['d','d','d']]

d    5
d    5
d    5
dtype: int64

In [11]:
obj2['x'] = 7   # yangi indeks va element qo'shish
obj2

a    6
b    3
c    2
d    5
x    7
dtype: int64

In [12]:
#  filtrga misol
obj2[obj2>4]

a    6
d    5
x    7
dtype: int64

In [13]:
np.sort(obj2)   # tartiblangan ko'rinishi (asl ma'lumot o'zgarmaydi)

array([2, 3, 5, 6, 7])

In [14]:
obj2*2

a    12
b     6
c     4
d    10
x    14
dtype: int64

In [15]:
np.exp(obj2)

a     403.428793
b      20.085537
c       7.389056
d     148.413159
x    1096.633158
dtype: float64

# **# 1 *Lug'atdan  Series***

In [16]:
# Dictionary
cars_dict = {'Malibu':40000, 'Lacetti':20000, 'Toyota':45000, 'Mazda':52000, 'Honda':38000}
type(cars_dict)

dict

In [17]:
# Series from dict
cars1 = Series(cars_dict)
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [18]:
type(cars1)

pandas.core.series.Series

In [19]:
'Malibu' in cars1

True

In [20]:
'BMW' in cars1

False

In [21]:
cars1['Toyota']

45000

In [22]:
models = ['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota', 'BMW']

In [23]:
cars2 = Series(cars_dict, index = models)
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [24]:
# cars2['Jaguar'] = 30000
# cars2

# **# 2** ***Series metodlari***

In [25]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [26]:
# isnull()
cars2.isnull()

Honda      False
Mazda      False
Lacetti    False
Jaguar      True
Malibu     False
Toyota     False
BMW         True
dtype: bool

In [27]:
# notnull()
cars2.notnull()

Honda       True
Mazda       True
Lacetti     True
Jaguar     False
Malibu      True
Toyota      True
BMW        False
dtype: bool

In [28]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
dtype: float64

In [29]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [30]:
# Qo'shish
cars1+cars2

BMW             NaN
Honda       76000.0
Jaguar          NaN
Lacetti     40000.0
Malibu      80000.0
Mazda      104000.0
Toyota      90000.0
dtype: float64

In [31]:
# Nom berish (name), (index.name)
cars2.name = 'Avtosalon'
cars2.index.name = 'Car Models'

In [32]:
cars2

Car Models
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
Name: Avtosalon, dtype: float64

In [33]:
cars2.name

'Avtosalon'

In [34]:
cars2.index.name

'Car Models'

## **`Series` obyektiga oid ba'zi parametr va metodlar**

---




In [54]:
cars2

Car Models
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jaguar         NaN
Malibu     40000.0
Toyota     45000.0
BMW            NaN
Name: Avtosalon, dtype: float64

In [35]:
cars2.index    # .indexes

Index(['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota', 'BMW'], dtype='object', name='Car Models')

In [36]:
cars2.values    # .values

array([38000., 52000., 20000.,    nan, 40000., 45000.,    nan])

In [37]:
# .hasnans
cars2.hasnans   # NaN qiymatlar borligi "True" yo'qligi "False"

True

In [38]:
# dtype
cars2.dtype

dtype('float64')

In [50]:
cars2.is_unique    # qiymatlar takrorlanmas ekanini tekshirish

False

In [51]:
cars2.shape    # Series hajmi

(7,)

In [52]:
cars2.size    # Series hajmi

7

In [53]:
# iloc
cars2.iloc[2]    # ma'lumotlarga indeks tartib raqami bo'yicha murojaat qilish

20000.0

In [56]:
cars2.iloc[-1]

nan

In [57]:
cars2['Honda']    # ma'lumotlarga indeks bo'yicha murojaat qilish

38000.0

In [59]:
# loc
cars2.loc['Toyota']    # ma'lumotlarga indeks bo'yicha murojaat qilish

45000.0

In [61]:
cars2.max()    # max qiymat 

52000.0

In [62]:
cars2.min()    # min qiymat

20000.0

In [64]:
cars2.mean()    # o'rtacha qiymat

39000.0

In [80]:
cars2.sum()    # cars2 sum

39000.0

In [69]:
np.sum(cars2)    # cars2 sum

195000.0

In [83]:
next = " Keyingi dars DataFrame ma'lumotlar tuzilmasi "